import type { Plan } from '../../types';

export const mockPlans: Plan[] = [
  {
    id: 'free',
    ad: 'Fərdi (Pulsuz)',
    təsvir: 'Ayda 5 elan yerləşdirmə',
    qiymət: 0,
    valyuta: 'AZN',
    xüsusiyyətlər: ['Ayda 5 elan', 'Əsas statistika'],
    tip: 'subscription',
  },
  {
    id: 'business-monthly',
    ad: 'Biznes (Aylıq)',
    təsvir: 'Limitsiz elan yerləşdirmə',
    qiymət: 79,
    valyuta: 'AZN',
    dövr: 'aylıq',
    xüsusiyyətlər: ['Limitsiz elan', 'Biznes profil badge', 'Statistika paneli'],
    tip: 'subscription',
  },
  {
    id: 'business-yearly',
    ad: 'Biznes (İllik)',
    təsvir: 'Limitsiz elan yerləşdirmə — 2 ay pulsuz',
    qiymət: 790,
    valyuta: 'AZN',
    dövr: 'illik',
    xüsusiyyətlər: ['Limitsiz elan', 'Biznes profil badge', 'Statistika paneli', '2 ay pulsuz (10 ay qiymətinə)'],
    tip: 'subscription',
  },
  {
    id: 'vip',
    ad: 'VIP Elan',
    təsvir: 'Elan siyahında yuxarıda görünüm',
    qiymət: 17,
    valyuta: 'AZN',
    xüsusiyyətlər: ['Siyahıda yuxarı mövqe', 'Cyan badge', 'Vurğulanmış kart'],
    tip: 'vip_tier',
  },
  {
    id: 'premium_vip',
    ad: 'Premium VIP Elan',
    təsvir: 'Ana səhifədə xüsusi görünüm',
    qiymət: 42,
    valyuta: 'AZN',
    xüsusiyyətlər: ['Siyahının başında', 'Qızılı badge', 'Böyük kart', 'Ana səhifədə feature'],
    tip: 'vip_tier',
  },
];
